In [13]:
items_per_sec = 3583832/30

In [5]:
s = "104847962 3583832 1212568077 114894281 3890048781 333451605 1520059863 217361990 310308287 12785610 3492562455 292968049 1901414562 516150861 2474299950 152867148 3394639029 59690410 862612782 176128197"

In [19]:
sum([int(x) for x in s.split()[1::2]]) / items_per_sec / 3600

4.3712102552984256

In [21]:
([int(x) for x in s.split()[1::2]])

[3583832,
 114894281,
 333451605,
 217361990,
 12785610,
 292968049,
 516150861,
 152867148,
 59690410,
 176128197]

In [22]:
min([4283162641, 780711947, 194991402, 13286163, 3191770485, 295741385, 2008786, 332248829, 749391108, 412475024])

2008786

In [23]:
dst_src_range = """2023441036 2044296880 396074363
2419515399 3839972576 454994720
274688417 699823315 258919718
533608135 0 431744151
965352286 431744151 161125324
3391658630 2936663910 903308666
200749950 1177785526 73938467
2874510119 1440389999 315892137
1916089471 2440371243 20593195
0 977035576 200749950
1936682666 1957538510 86758370
1440389999 2902130623 34533287
1126477610 592869475 106953840
3190402256 1756282136 201256374
1474923286 2460964438 441166185
1233431450 958743033 18292543"""

In [49]:
src_range_dst = sorted([list(np.array(l.split())[[1, 2, 0]]) for l in dst_src_range.split("\n")])
src_range_dst

[['0', '431744151', '533608135'],
 ['1177785526', '73938467', '200749950'],
 ['1440389999', '315892137', '2874510119'],
 ['1756282136', '201256374', '3190402256'],
 ['1957538510', '86758370', '1936682666'],
 ['2044296880', '396074363', '2023441036'],
 ['2440371243', '20593195', '1916089471'],
 ['2460964438', '441166185', '1474923286'],
 ['2902130623', '34533287', '1440389999'],
 ['2936663910', '903308666', '3391658630'],
 ['3839972576', '454994720', '2419515399'],
 ['431744151', '161125324', '965352286'],
 ['592869475', '106953840', '1126477610'],
 ['699823315', '258919718', '274688417'],
 ['958743033', '18292543', '1233431450'],
 ['977035576', '200749950', '0']]

In [57]:
arr = np.array(src_range_dst).astype(np.int64)
arr

array([[         0,  431744151,  533608135],
       [1177785526,   73938467,  200749950],
       [1440389999,  315892137, 2874510119],
       [1756282136,  201256374, 3190402256],
       [1957538510,   86758370, 1936682666],
       [2044296880,  396074363, 2023441036],
       [2440371243,   20593195, 1916089471],
       [2460964438,  441166185, 1474923286],
       [2902130623,   34533287, 1440389999],
       [2936663910,  903308666, 3391658630],
       [3839972576,  454994720, 2419515399],
       [ 431744151,  161125324,  965352286],
       [ 592869475,  106953840, 1126477610],
       [ 699823315,  258919718,  274688417],
       [ 958743033,   18292543, 1233431450],
       [ 977035576,  200749950,          0]])

In [63]:
arr2 = arr[arr[:, 0].argsort()]

In [68]:
arr2

array([[         0,  431744151,  533608135],
       [ 431744151,  161125324,  965352286],
       [ 592869475,  106953840, 1126477610],
       [ 699823315,  258919718,  274688417],
       [ 958743033,   18292543, 1233431450],
       [ 977035576,  200749950,          0],
       [1177785526,   73938467,  200749950],
       [1440389999,  315892137, 2874510119],
       [1756282136,  201256374, 3190402256],
       [1957538510,   86758370, 1936682666],
       [2044296880,  396074363, 2023441036],
       [2440371243,   20593195, 1916089471],
       [2460964438,  441166185, 1474923286],
       [2902130623,   34533287, 1440389999],
       [2936663910,  903308666, 3391658630],
       [3839972576,  454994720, 2419515399]])

In [89]:
np.hstack([arr2[:,:2], arr2[:, :2].sum(axis=1)[None, :].T])

array([[         0,  431744151,  431744151],
       [ 431744151,  161125324,  592869475],
       [ 592869475,  106953840,  699823315],
       [ 699823315,  258919718,  958743033],
       [ 958743033,   18292543,  977035576],
       [ 977035576,  200749950, 1177785526],
       [1177785526,   73938467, 1251723993],
       [1440389999,  315892137, 1756282136],
       [1756282136,  201256374, 1957538510],
       [1957538510,   86758370, 2044296880],
       [2044296880,  396074363, 2440371243],
       [2440371243,   20593195, 2460964438],
       [2460964438,  441166185, 2902130623],
       [2902130623,   34533287, 2936663910],
       [2936663910,  903308666, 3839972576],
       [3839972576,  454994720, 4294967296]])

In [39]:
import numpy as np
np.array([1,2,3])[[1, 0, 2]]

array([2, 1, 3])